# ==============================================================
# GATRA PRODUCTION PROPERTIES
# ==============================================================

# 1. Database Configuration (Using Environment Variables)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. JPA / Hibernate (Optimized for Production)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 3. Security & JWT Configuration
# Diambil dari Environment Variables di Azure
app.frontend.url=${FRONTEND_URL}
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# 4. Google OAuth2 Configuration
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email

# 5. Logging (Hanya mencatat error/warning agar hemat storage & CPU)
logging.level.root=WARN
logging.level.id.ac.ui.cs.advprog=INFO
logging.level.org.springframework.web=ERROR

# 6. Server Configuration
server.error.include-stacktrace=never
server.forward-headers-strategy=native