name: Continuous Integration (CI)

on:
  push:
    branches: [ "main", "staging" ]
  pull_request:
    branches: [ "main", "staging" ]

jobs:
  # CI (Quality Check)
  test:
    name: Run tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java toolchain
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Run unit tests
        run: ./gradlew test

  # CD (Dummy Deployment)
  deploy:
    name: Dummy Deployment
    needs: test
    # the job will be executed if the 'test' has succeed (green)


    if: github.event_name == 'push' # prevent deployment before pull request
    runs-on: ubuntu-22.04
    steps:
      - name: Deploying...
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "Deploying dummy build to PRODUCTION environment..."
          else
            echo "Deploying dummy build to STAGING environment..."
          fi